# Generated by Django 4.1.7 on 2023-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobportal',
            old_name='status',
            new_name='currenlty_working',
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
